{% set name = "pytest-reportlog" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 75aec3a92bb53456c3e028605a636579d26f31c6f1e035ad9f706c203cfcb74e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools_scm
  run:
    - pytest >=5.2
    - python >=3.5

test:
  imports:
    - pytest_reportlog
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytest-dev/pytest-reportlog
  summary: Replacement for the --resultlog option, focused in simplicity and extensibility
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
