{% set name = "pytest-reportlog" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7b1644039babcb9cbbce31f4d9407d7131b10b1fc49e1e7cbfa27c2918b95b1a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools_scm
  run:
    - pytest >=5.2
    - python >=3.5

test:
  imports:
    - pytest_reportlog
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytest-dev/pytest-reportlog
  summary: Replacement for the --resultlog option, focused in simplicity and extensibility
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
